https://github.com/genisysram/case.gitlanguage: python
sudo: false
cache: false
python:
    - '3.5'
os: linux
arch:
  - ppc64le
  - amd64
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.6
    - TOXENV=2.7
    - TOXENV=3.3
    - TOXENV=3.4
    - TOXENV=3.4
    - TOXENV=pypy
    - TOXENV=3.5
    - TOXENV=flake8
    - TOXENV=flakeplus
    - TOXENV=apicheck
before_install:
  - sudo apt-get -y install python  
  - sudo apt-get install -y pip
  - sudo apt-get install -y python3-pip
install: travis_retry pip install -U tox
script: tox -v -- -v
after_success:
  - .tox/$TRAVIS_PYTHON_VERSION/bin/coverage xml
  - .tox/$TRAVIS_PYTHON_VERSION/bin/codecov -e TOXENV
